version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6.1-jdk-8

    steps:
      - checkout

      - run:
          name: Run Command in Background
          command: mvn clean install exec:java -Dexec.mainClass="com.mycompany.app.App"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
